# This is a config for E2B sandbox template.
# You can use template ID (0sxrdhddzyxffrzvuqc9) or template name (vibe-nextjs-manisha-123) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-manisha-123") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-manisha-123") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-manisha-123')

team_id = "3596000c-f5b1-49cb-b6c0-abfc61e47cef"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-manisha-123"
template_id = "0sxrdhddzyxffrzvuqc9"
